[tool.poetry]
name = "py-engineering-hw6"
version = "0.1.0"
description = ""
authors = ["Abboth <Alexmikhailov90@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
faker = "^35.0.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
